DataBase:
  DBType: mysql
  UserName: root
  Password: Woquz159357!
  Host: 127.0.0.1:3306
  DBName: myservice
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
App:
  DefaultPageSize: 10
  MaxPageSize: 50
  LogSavePath: logs
  LogFileName: app
  LogFileExt: .log
  UsclientPath: /home/lighthouse/service
Server:
  RunMode: release
  HttpPort: 81
  ReadTimeOut: 60
  WriteTimeOut: 60
JWT:
  Expire: 7200
Redis:
  RedisAddr: 127.0.0.1:6379
  RedisPassword: Woquz1593571!a
  RedisDB: 0
